// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxAXhvlK9M3jHtBaF3eV-sMAvJJruDgwk',
    appId: '1:934104097670:web:3533294d9f73f4dfad4207',
    messagingSenderId: '934104097670',
    projectId: 'flutter-app-ad362',
    authDomain: 'flutter-app-ad362.firebaseapp.com',
    storageBucket: 'flutter-app-ad362.firebasestorage.app',
    measurementId: 'G-8Q7E66PSEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW5YLWCQrdZ_PjgvdPuXp0J3XW1wgNsIg',
    appId: '1:934104097670:android:99594b8e80711cd4ad4207',
    messagingSenderId: '934104097670',
    projectId: 'flutter-app-ad362',
    storageBucket: 'flutter-app-ad362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC3UURw30pt114Fy2TrBkID41xSs70BM4',
    appId: '1:934104097670:ios:0f05edb844d167b5ad4207',
    messagingSenderId: '934104097670',
    projectId: 'flutter-app-ad362',
    storageBucket: 'flutter-app-ad362.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC3UURw30pt114Fy2TrBkID41xSs70BM4',
    appId: '1:934104097670:ios:0f05edb844d167b5ad4207',
    messagingSenderId: '934104097670',
    projectId: 'flutter-app-ad362',
    storageBucket: 'flutter-app-ad362.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxAXhvlK9M3jHtBaF3eV-sMAvJJruDgwk',
    appId: '1:934104097670:web:ac8ea76f9e6fd5a4ad4207',
    messagingSenderId: '934104097670',
    projectId: 'flutter-app-ad362',
    authDomain: 'flutter-app-ad362.firebaseapp.com',
    storageBucket: 'flutter-app-ad362.firebasestorage.app',
    measurementId: 'G-CKY3V04ECN',
  );
}
